name: graduation_project
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  retrofit: ^4.6.0
  retrofit_generator: ^9.1.9
  ticket_widget: ^1.0.2
  dotted_line: ^3.2.3
  dotted_border: ^2.1.0
  flutter_rating_bar: ^4.0.1
  dio: ^5.8.0+1
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  awesome_dialog: ^3.2.1
  flutter_otp_text_field: ^1.5.1+1
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  flutter_keyboard_visibility: ^6.0.0
  stomp_dart_client: ^2.1.3
  web_socket_channel: ^3.0.3
  flutter_native_splash: ^2.4.6
  flutter_localization: ^0.3.3
  zego_uikit_prebuilt_call: ^4.17.7
  zego_uikit_signaling_plugin: ^2.8.15
  flutter_stripe: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/aqqar_link2.png"
  min_sdk_android: 21
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/aqqar_link2.png
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
