name: graduation_project
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  retrofit_generator: ^9.1.9
  flutter_localization: ^0.3.2
  ticket_widget: ^1.0.2
  dotted_line: ^3.2.3
  dotted_border: ^2.1.0
  flutter_rating_bar: ^4.0.1
  dio: ^5.8.0+1
  dartz: ^0.10.1
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  json_annotation: ^4.9.
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  awesome_dialog: ^3.2.1
  flutter_otp_text_field: ^1.5.1+1
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.0.0


intl: ^0.19.0
flutter_localization: ^0.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/property1.jpg
    - assets/images/property2.jpg
    - assets/images/property3.jpg
    - assets/images/property4.jpg
    - assets/images/sendRequest.png
    - assets/images/MyAppointement.png
    - assets/images/PublishTicket.png
    - assets/images/SearchExperts.png
    - assets/images/expert.jpg
    - assets/images/garden.jpg
    - assets/images/villa.jpg
    - assets/images/store.jpg
    - assets/images/balcony.jpg
    - assets/images/bedroom.jpg
    - assets/images/livingroom.jpg
    - assets/images/follow.png
    - assets/images/user.png
    - assets/images/communication.png
    - assets/images/walletBackground.jpg

