name: graduation_project
description: "A new Flutter project."
publish_to: 'none'  # Prevents accidental publication

version: 1.0.0+1

environment:
  sdk: ^3.5.3  # Updated to match your current Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
 # assets:
 #   - assets/my_icon.png
  #  - assets/background.png