name: graduation_project
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  retrofit_generator: ^9.1.9
  ticket_widget: ^1.0.2
  dotted_line: ^3.2.3
  dotted_border: ^2.1.0
  flutter_rating_bar: ^4.0.1
  dio: ^5.8.0+1
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  awesome_dialog: ^3.2.1
  flutter_otp_text_field: ^1.5.1+1
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  flutter_localization: ^0.3.2
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/villa.jpg
  android: true
  ios: true
  android_gravity: fill

flutter:
  uses-material-design: true

  assets:
    - assets/images/
