// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA46b48MvHyZYBXFZucn_fXckL_fA8DdOA',
    appId: '1:310769094793:web:dcbc7781214202b7427658',
    messagingSenderId: '310769094793',
    projectId: 'realestate-bb970',
    authDomain: 'realestate-bb970.firebaseapp.com',
    storageBucket: 'realestate-bb970.firebasestorage.app',
    measurementId: 'G-DBY9NDH3H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0QivkiQvujXs3PU3E9gKUcAviKg9fW88',
    appId: '1:310769094793:android:09d97be7cbe25e23427658',
    messagingSenderId: '310769094793',
    projectId: 'realestate-bb970',
    storageBucket: 'realestate-bb970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2c1EjGFRlg03S9hv0pGuMYGjqHwyxyoo',
    appId: '1:310769094793:ios:49e2585731402e82427658',
    messagingSenderId: '310769094793',
    projectId: 'realestate-bb970',
    storageBucket: 'realestate-bb970.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2c1EjGFRlg03S9hv0pGuMYGjqHwyxyoo',
    appId: '1:310769094793:ios:49e2585731402e82427658',
    messagingSenderId: '310769094793',
    projectId: 'realestate-bb970',
    storageBucket: 'realestate-bb970.firebasestorage.app',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA46b48MvHyZYBXFZucn_fXckL_fA8DdOA',
    appId: '1:310769094793:web:40380fa8dca26201427658',
    messagingSenderId: '310769094793',
    projectId: 'realestate-bb970',
    authDomain: 'realestate-bb970.firebaseapp.com',
    storageBucket: 'realestate-bb970.firebasestorage.app',
    measurementId: 'G-M14YJF2X6B',
  );
}
