
import 'package:flutter/material.dart';

class AppTheme {
  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff246488),
      surfaceTint: Color(0xff246488),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffc8e6ff),
      onPrimaryContainer: Color(0xff001e2e),
      secondary: Color(0xff2d628b),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffcde5ff),
      onSecondaryContainer: Color(0xff001d32),
      tertiary: Color(0xff6c538c),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffeedcff),
      onTertiaryContainer: Color(0xff260d44),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff410002),
      surface: Color(0xfff6fafe),
      onSurface: Color(0xff181c20),
      onSurfaceVariant: Color(0xff41484d),
      outline: Color(0xff71787e),
      outlineVariant: Color(0xffc1c7ce),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff2d3135),
      inversePrimary: Color(0xff94cdf6),
      primaryFixed: Color(0xffc8e6ff),
      onPrimaryFixed: Color(0xff001e2e),
      primaryFixedDim: Color(0xff94cdf6),
      onPrimaryFixedVariant: Color(0xff004c6d),
      secondaryFixed: Color(0xffcde5ff),
      onSecondaryFixed: Color(0xff001d32),
      secondaryFixedDim: Color(0xff99ccfa),
      onSecondaryFixedVariant: Color(0xff094a72),
      tertiaryFixed: Color(0xffeedcff),
      onTertiaryFixed: Color(0xff260d44),
      tertiaryFixedDim: Color(0xffd8bafb),
      onTertiaryFixedVariant: Color(0xff533b72),
      surfaceDim: Color(0xffd7dadf),
      surfaceBright: Color(0xfff6fafe),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff1f4f9),
      surfaceContainer: Color(0xffebeef3),
      surfaceContainerHigh: Color(0xffe5e8ed),
      surfaceContainerHighest: Color(0xffdfe3e7),
    );
  }
}
